### ISSUE TITLE
Update ESP32 with improvements made on ESP8266

### ISSUE THREAD

**Issue by Albin76** [Albin76/Home_assistant_MQTT#23]
- [x] Wifi.persistence
- [x] If BME280 wierd values measure again once (Issue #21 
- [x] Add code for sleep when esp_now_register_send_cb returns ok #20 
- [x] Short and long sleep after faults enhancement #19 
- [x] Add define for measure battery or not. enhancement #14 
- [x] Add check for nan and unrealistic values. enhancement #12
